export type AllNavParamList = {
  SplashScreen: undefined;
  Onboarding: undefined;
  Login: undefined;
  SignUp: undefined;
  ForgotPassword: undefined;
  VerifyOtp: { from: string; email: string };
  ResetPassword: { email: string };
  Dashboard: undefined;
  HomeStack: undefined;
  HomeScreen: undefined;
  ProductDetailScreen: undefined;
  OrderDetailScreen: undefined;
  WishlistStack: undefined;
  WishlistScreen: undefined;
  ProfileStack: undefined;
  ProfileScreen: undefined;
  ChangePassword: undefined;
  EditProfile: undefined;
  CartStack: undefined;
  CartScreen: undefined;
  PaymentScreen: undefined;
  NotificationScreen: undefined;
  AddressScreen: undefined;
};
